name: Exercice 4
on:
  workflow_dispatch:
jobs:
  jobs1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v6.1.0
  jobs2:
    needs: jobs1
    runs-on : ubuntu-latest
    steps:
      - run : node -v
      
