name : ExVar
on:  
  workflow_dispatch:
job:
 runs-on: ubuntu-latest
 env:
 VARIABLE: jaune
 NOMVARIABLE: salut
 steps:
 - run: echo $VARIABLE
 - run: echo $VARIABLE
 - id: monStep
 run: echo "::set-output name=NOMVARIABLE::hello"
   - run: echo **${{ steps.monStep.outputs.NOMVARIABLE }}**
